// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tickie.Manager.Data;

#nullable disable

namespace Tickie.Manager.Migrations
{
    [DbContext(typeof(TickieDbContext))]
    [Migration("20261009043230_AddLabels")]
    partial class AddLabels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Tickie.Manager.Entities.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("Tickie.Manager.Entities.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.HasIndex("ProjectId", "Order")
                        .IsUnique();

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("Tickie.Manager.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BaselineFrozenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FolderPath")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Tickie.Manager.Entities.StatusChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("StatusChanges");
                });

            modelBuilder.Entity("Tickie.Manager.Entities.StatusChangeTicket", b =>
                {
                    b.Property<int>("StatusChangeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StatusChangeId", "TicketId");

                    b.HasIndex("TicketId");

                    b.ToTable("StatusChangeTickets");
                });

            modelBuilder.Entity("Tickie.Manager.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("EstimatedHours")
                        .HasColumnType("REAL");

                    b.Property<int>("PhaseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Tickie.Manager.Entities.TicketDependency", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrerequisiteTicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TicketId", "PrerequisiteTicketId");

                    b.HasIndex("PrerequisiteTicketId");

                    b.ToTable("TicketDependencies", t =>
                        {
                            t.HasCheckConstraint("CK_TicketDependencies_NotSelf", "\"TicketId\" <> \"PrerequisiteTicketId\"");
                        });
                });

            modelBuilder.Entity("Tickie.Manager.Entities.TicketLabel", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TicketId", "LabelId");

                    b.HasIndex("LabelId");

                    b.ToTable("TicketLabels");
                });

            modelBuilder.Entity("Tickie.Manager.Entities.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Tickie.Manager.Entities.Label", b =>
                {
                    b.HasOne("Tickie.Manager.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tickie.Manager.Entities.Phase", b =>
                {
                    b.HasOne("Tickie.Manager.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tickie.Manager.Entities.StatusChange", b =>
                {
                    b.HasOne("Tickie.Manager.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tickie.Manager.Entities.StatusChangeTicket", b =>
                {
                    b.HasOne("Tickie.Manager.Entities.StatusChange", null)
                        .WithMany()
                        .HasForeignKey("StatusChangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tickie.Manager.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tickie.Manager.Entities.Ticket", b =>
                {
                    b.HasOne("Tickie.Manager.Entities.Phase", null)
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tickie.Manager.Entities.TicketDependency", b =>
                {
                    b.HasOne("Tickie.Manager.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("PrerequisiteTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tickie.Manager.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tickie.Manager.Entities.TicketLabel", b =>
                {
                    b.HasOne("Tickie.Manager.Entities.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tickie.Manager.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
